### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by stepersy** [kriseniprak/MyDbook-Scraper#1]
Hi, i'm interested in your project, how to use it?

**Comment by kriseniprak** [comment]
- Go to https://mydbook.giuntitvp.it/ from your browser;
- Select a book that you own;
- You will have something like this in the URL: https://mydbook.giuntitvp.it/app/books/GIAC90_G9075484A/;
- Copy the ID of the book (in this case GIAC90_G9075484A);
- Run the scraping software, and log in to your account;
- Paste the book ID into the provided field;
- Enter the correct number of pages;
- Click the "Start scraping" button.

**Comment by nicoursi** [comment]
For building you need to install Visual studio and then compile the .exe file. Only the you can run the software and follow the instuctions above!

**Comment by ArcadeZone** [comment]
buongiorno, sto provando ad usare questo repository ma come si fa ad eseguirlo?
